### ISSUE TITLE
Not downloading iOS 4.3.5 (and other 4.3.4, 4.3.3)

### ISSUE THREAD

**Issue by Maciekwulf** [Zurac-Apps/4tify-iPad2#2]
I can't get pass the: ./iOS4.sh <Model> <Version> <IP-Address> 
when I type it, terminal outputs: "./iOS4.sh 2,2 4.3.5 192.168.1.27
dyld: Library not loaded: /usr/local/opt/libzip/lib/libzip.5.dylib
  Referenced from: /Users/maciejwulf/Downloads/4tify-iPad2-master/support_files/4.3.5/Patches2,2/./pzb
  Reason: image not found
./iOS4.sh: line 1719: 31689 Abort trap: 6           ./pzb -g 038-2278-002.dmg https://secure-appldnld.apple.com/iPhone4/041-1961.20110721.zigyd/iPad2,2_4.3.5_8L1_Restore.ipsw"
I have tried restoring my iPad again, I have also tried using other Mac. 
I've tried on version 1.0 and newer.

**Comment by marko1605** [comment]
This issue seems to be with downloading the required files. I contacted the developer through reddit and he sent me some files which fixed the issue. Fortunately I can't share it with you because it is for the ipad 2,1 and for ios 4.3.4
