### ISSUE TITLE
iPad 2,1 recovery loop on running the 4tify app

### ISSUE THREAD

**Issue by arandomusernam** [Zurac-Apps/4tify-iPad2#5]
I have an iPad 2,1 which always boots to recovery mode after running the 4tify app. I can get back on to ios 6 just fine, but I can't boot to iOS 4. I've reinstalled the 4tify app numerous times.

**Comment by elislays08** [comment]
How did you fix this?

**Comment by arandomusernam** [comment]
I did not fix this. It turned out my iPad never ran iOS 4, which is required to use 4tify.
